small_group:
  _target_: ptls_extension_2024_research.nn.trx_encoder.encoders.PretrainedGraphItemEmbedder
  embeddings:
    _target_: torch.load
    f: models/pretrained_gnn_models/wl-0.5_gnn-GraphSAGE_res-True_wd-0.01/200.pt
    # map_location: ${device}
  item_id2graph_id: 
    _target_: torch.load
    f: data/graphs/weighted/item_id2train_graph_id.pt
    # map_location: ${device}
  device: 
    _target_: torch.device
    device: ${device} 
  freeze: false
