defaults:
  - _self_
  - dataset_unsupervised/parquet
  - inference/default
  - inference/seq_encoder/pretrained
  - data_module: ptls_coles_memory
  - trx_embedding_layers: all_features

graph_path: ./data/graphs/weighted

seed_everything: 42
logger_name: mles_model
model_path: models/mles_model.p
embed_file_name: mles_embeddings

device: cuda

trainer: 
  accelerator: ${device}
  max_epochs: 150
  enable_checkpointing: false
  deterministic: true

pl_module:
  _target_: ptls.frames.coles.CoLESModule
  validation_metric:
    _target_: ptls.frames.coles.metric.BatchRecallTopK
    K: 4
    metric: cosine
  seq_encoder:
    _target_: ptls.nn.RnnSeqEncoder
    trx_encoder: 
      _target_: ptls.nn.TrxEncoder
      norm_embeddings: false
      embeddings_noise: 0.003
      embeddings: ${trx_embedding_layers}
      numeric_values: 
        amount: identity
    type: gru
    hidden_size: 1024
    bidir: false
    trainable_starter: static
  head:
    _target_: ptls.nn.Head
    use_norm_encoder: true
    input_size: ${pl_module.seq_encoder.hidden_size}
  loss:
    _target_: ptls.frames.coles.losses.ContrastiveLoss
    margin: 0.5
    sampling_strategy:
      _target_: ptls.frames.coles.sampling_strategies.HardNegativePairSelector
      neg_count: 5
  optimizer_partial:
    _partial_: true
    _target_: torch.optim.Adam
    lr: 0.002
    weight_decay: 0.0
  lr_scheduler_partial:
    _partial_: true
    _target_: torch.optim.lr_scheduler.StepLR
    step_size: 10
    gamma: 0.9025
