defaults:
  - _self_
  - dataset_unsupervised: parquet
  - inference: default
  - inference/seq_encoder/pretrained
  - data_module: ptls_coles_memory
  - trx_embedding_layers: all_except_item_id

seed_everything: 42
logger_name: barlow_twins_model
model_path: models/barlow_twins_model.p
embed_file_name: barlow_twins_embeddings


device: cuda

trainer: 
  accelerator: ${device}
  max_epochs: 150
  enable_checkpointing: false
  deterministic: true

pl_module:
  _target_: ptls.frames.coles.CoLESModule
  validation_metric:
    _target_: ptls.frames.coles.metric.BatchRecallTopK
    K: 1
    metric: cosine
  seq_encoder:
    _target_: ptls.nn.RnnSeqEncoder
    trx_encoder:
      _target_: ptls.nn.TrxEncoder
      norm_embeddings: false
      embeddings_noise: 0.003
      embeddings: ${trx_embedding_layers}
      numeric_values: 
        price: identity
        request_cnt: identity
    type: gru
    hidden_size: 800
    bidir: false
    trainable_starter: static
  head:
    _target_: ptls.nn.Head
    input_size: ${pl_module.seq_encoder.hidden_size}
    hidden_layers_sizes: [256, 256]
    use_batch_norm: true
  loss:
    _target_: ptls.frames.coles.losses.BarlowTwinsLoss
    lambd: 0.04
  optimizer_partial:
    _partial_: true
    _target_: torch.optim.Adam
    lr: 0.001
    weight_decay: 0.0
  lr_scheduler_partial:
    _partial_: true
    _target_: torch.optim.lr_scheduler.StepLR
    step_size: 30
    gamma: 0.9025